# Generated by Django 6.1.1 on 2026-09-26 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(max_length=255)),
                ('telefono_id', models.CharField(max_length=255)),
                ('token_acceso', models.CharField(max_length=255)),
                ('prompt_sistema_ia', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CicloFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('conteo_mensajes_ia', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='NodoBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_nodo', models.CharField(choices=[('MENU', 'Menu'), ('TEXT', 'Texto'), ('AI_AGENT', 'Agente IA')], max_length=50)),
                ('contenido_mensaje', models.TextField()),
                ('es_nodo_inicial', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_esperada', models.CharField(max_length=255)),
                ('nodo_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_salida', to='core.nodobot')),
                ('nodo_siguiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_entrada', to='core.nodobot')),
            ],
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_cliente', models.CharField(max_length=255)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nodo_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nodobot')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=50)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('sesion_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sesionusuario')),
            ],
        ),
    ]
